name: Setup wiki build toolchain
description: Sets up the mdBook based wiki toolchain

runs:
  using: "composite"

  steps:
    - name: Download mdBook
      shell: bash
      run: |
        set +x

        version="v0.4.40"

        cd /tmp
        archive="mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz"
        wget "https://github.com/rust-lang/mdBook/releases/download/v0.4.40/${archive}"
        tar xzvf "${archive}"
        sudo mv mdbook /usr/bin

        mdbook --version
