---
on: 
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and Publish

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: ./.github/actions/setup-toolchain

      - name: Build
        run: mdbook build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 03654dab23842c712e474f409d58f55c
          command: pages deploy out --project-name=makerspace-wiki
