---
on: 
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and Publish

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download mdBook
        run: |
          set +x

          version="v0.4.40"

          cd /tmp
          archive="mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz"
          wget "https://github.com/rust-lang/mdBook/releases/download/v0.4.40/${archive}"
          tar xzvf "${archive}"
          sudo mv mdbook /usr/bin

          mdbook --version

      - name: Build
        run: mdbook build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 03654dab23842c712e474f409d58f55c
          command: pages deploy out --project-name=makerspace-wiki
